name: serial
description: Serial port for flutter. Wrapper around the `window.navigator.serial` for web platform.
version: 0.0.3
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_serial/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.4

dev_dependencies:
  test: ^1.22.0
  lints: ^2.0.0
